# Generated by Django 2.1.7 on 2019-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='ここに本文を入力してください', verbose_name='text'),
            preserve_default=False,
        ),
    ]
